myproject/myproject/urls.py
"""myproject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from boards import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^boards/(?P<pk>\d+)/new/$',views.new_topic,name="new_topic"),
    url(r'^boards/(?P<pk>\d+)/$',views.baord_topic,name="board_topic"),
    url(r'^admin/', admin.site.urls),
]

myproject/boards/models.py
'''
Author: huangjy
Date: 2020-11-19 00:35:48
LastEditTime: 2020-11-28 22:36:07
LastEditors: huangjy
Description: 模型，创建数据库对象
FilePath: /myproject/boards/models.py
'''
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

'''
description:  创建数据库表的实体，这些信息将用于创建数据库列
param {*}
return {*}
'''
class Board(models.Model):
    #唯一值
    name = models.CharField(max_length=30,unique=True)
    description = models.CharField(max_length=100) 
    def __str__(self):
        #return  self.id,self.name,self.description
        return "板块id：%d, 板块名称：%s,描述：%s" %(self.id,self.name,self.description)  
    
class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board,related_name="topics",on_delete=models.CASCADE)
    starter = models.ForeignKey(User,related_name="topics",on_delete=models.CASCADE)


class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic,related_name='posts',on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add= True)
    update_at = models.DateTimeField(null=True)
    create_by =models.ForeignKey(User,related_name="posts",on_delete=models.CASCADE)
    update_at = models.ForeignKey(User,null=True,related_name='+',on_delete=models.CASCADE)

    

myproject/boards/views.py
'''
Author: your name
Date: 2020-11-19 00:35:48
LastEditTime: 2020-11-28 22:38:29
LastEditors: huangjy
Description: 视图
FilePath: /myproject/boards/views.py
'''

from django.contrib.auth.models import User
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,Http404
from .models import Board,Post,Topic
# Create your views here.


#def home(request):
 #   return HttpResponse('Hello, World!')

'''
description: b板块列表页
param {*}
return {*}
'''
# def home(request):
#     boards = Board.objects.all()
#     boards_names = list()
#     for board in boards:
#         boards_names.append(board)
#     response_html = '<br>'.join('%s' %id for id in boards_names)
#     return HttpResponse(response_html)

def home(request):
    """
    定义首页页面
    """
    boards = Board.objects.all()
    return render(request,"home.html",{'boards':boards})

def baord_topic(request,pk):
    # try:
    #   board = Board.objects.get(pk=pk)
    # except Board.DoesNotExist:
    #     raise Http404
    board = get_object_or_404(Board,pk=pk)
    return render(request,"topic.html",{'board':board})


def new_topic(request,pk):
    
    board = get_object_or_404(Board,pk=pk)
    if request.method == 'POST':
        subject = request.POST['subject']
        message = request.POST['message']
        
        user = User.objects.first()
        
        topic = Topic.objects.create(
            subject = subject,
            board = board,
            starter=user
        )
        
        post =Post.objects.create(
            message = message,
            topic = topic,
            create_by = user
        )
        return redirect('board_topic',pk=board.pk)
    
    return render(request,"new_topic.html",{"board":board})

myproject/templates/base.html
<!--
 * @Author: huangjy
 * @Date: 2020-11-24 00:24:01
 * @LastEditors: huangjy
 * @LastEditTime: 2020-11-24 00:35:46
 * @Description: 母版页 其他模板都 extend(继承) 这个模板
-->

{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
      </div>
    </nav>

    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

myproject/templates/home.html
<!--
 * @Author: huangjy
 * @Date: 2020-11-22 10:52:41
 * @LastEditors: huangjy
 * @LastEditTime: 2020-11-24 00:32:35
 * @Description: file content
-->
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Board</th>
        <th>Posts</th>
        <th>Topics</th>
        <th>Last Post</th>
      </tr>
    </thead>
    <tbody>
      {% for board in boards %}
        <tr>
          <td>
            <a href="{% url 'board_topic' board.pk %}">{{ board.name }}</a>
            <small class="text-muted d-block">{{ board.description }}</small>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

myproject/templates/new_topic.html
<!--
 * @Author: huangjy
 * @Date: 2020-11-24 22:39:05
 * @LastEditors: huangjy
 * @LastEditTime: 2020-11-28 22:23:55
 * @Description: file content
-->
{% extends 'base.html' %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topic' board.pk %}">{{ board.name }}</a></li>
  <li class="breadcrumb-item active">New topic</li>
{% endblock %}
<!-- 保护post请求，避免外部站点或者应用程序向我们的应用程序提交数据的安全措施
应用程序每次接收一个 POST 时，都会先检查 CSRF Token。如果这个 request 没有 token，
或者这个 token是无效的，它就会抛弃提交的数据
<input type="hidden" name="csrfmiddlewaretoken" value="jG2o6aWj65YGaqzCpl0TYTg5jn6SctjzRZ9KmluifVx0IVaxlwh97YarZKs54Y32">
-->
{% block content %}
  <form method="post">
    
    {% csrf_token %}
    <div class="form-group">
      <label for="id_subject">Subject</label>
      <input type="text" class="form-control" id="id_subject" name="subject">
    </div>
    <div class="form-group">
      <label for="id_message">Message</label>
      <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
    </div>
    <button type="submit" class="btn btn-success">Post</button>
  </form>
{% endblock %}

myproject/templates/topic.html
<!--
 * @Author: huangjy
 * @Date: 2020-11-22 19:08:08
 * @LastEditors: huangjy
 * @LastEditTime: 2020-11-28 22:46:27
 * @Description: file content
-->

{% extends 'base.html' %}

{% block title %}
  {{ board.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item active">{{ board.name }}</li>
  <li class="breadcrumb-item" >New topic</li>
{% endblock %}

{% block content %}
<div class="mb-b">
  <a href="{% url 'new_topic' board.pk %}" class="btn btn-primary">New topic</a>
</div>
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Topic</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in board.topics.all %}
        <tr>
          <td>{{ topic.subject }}</td>
          <td>{{ topic.starter.username }}</td>
          <td>0</td>
          <td>0</td>
          <td>{{ topic.last_updated }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}